#!/usr/bin/env sh
. "$(dirname "$0")/h"

# Exit immediately on failure
set -e

echo "🔍 Running linter..."
npm run lint

# Compile TypeScript
echo "Compiling TypeScript.."
npm run typecheck

# Check if tests passed
if [ $? -ne 0 ]; then
  echo "❌ Found type errors! Please fix the errors before pushing."
  exit 1
fi

# Run tests
echo "Running tests.."
npm run test

# Check if tests passed
if [ $? -ne 0 ]; then
  echo "❌ Tests failed! Please fix the issues before pushing."
  exit 1
fi

echo "✅ Tests passed successfully. Pushing.."

